EIS.FEW/Controllers/GroupUserController.cs
using EIS.Core;
using EIS.Core.CustomView;
using EIS.Core.Domain;
using EIS.Core.IService;
using FX.Context;
using FX.Core;
using IdentityManagement.Domain;
using IdentityManagement.Service;
using log4net;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace EIS.FEW.Controllers
{
    [Authorize]
    public class GroupUserController : BaseController
    {
        private readonly IuserService UserDataService;
        private readonly INGUOIDUNGService _INGUOIDUNGService = IoC.Resolve<INGUOIDUNGService>();
        private NGUOIDUNG nguoidung = ((EISContext)FXContext.Current).CurrentNguoidung;
        private static readonly ILog log = LogManager.GetLogger(typeof(GroupUserController));

        //
        // GET: /GroupUser/

        public ActionResult Index()
        {
            var groupSrv = IoC.Resolve<INHOM_USERService>();
            var model = new UserGroupModelDetail();
            int a = groupSrv.Query.Where(o => o.USER_ID == nguoidung.ID).Count() > 0 ? groupSrv.Query.Where(o => o.USER_ID == nguoidung.ID).OrderByDescending(o => o.ID).FirstOrDefault().ID : 0;//
            model.Roles = GetListRoles().ToList();
            model.Groups = groupSrv.Query.Where(o=>o.USER_ID == nguoidung.ID).OrderByDescending(o=>o.ID).ToList() ?? new List<NHOM_USER>();
            ViewBag.DSUSER = UserRoleCallbackPanelCustom(a);
            Session["Group_LstRole"] = model.Roles;
            ViewBag.Content = RenderRazorViewToString("checkBoxLstRole", model.Roles);
            model.usersOfGroup = LoadUserOfGroupModel(a);
            return View(model);
        }

        public ActionResult CbbGroupCallBack()
        {
            var groupSrv = IoC.Resolve<INHOM_USERService>();
            var selectGroupUS = groupSrv.Query.Where(o => o.USER_ID == nguoidung.ID).ToList().OrderByDescending(o=>o.ID);
            //ViewBag.DescenNhom = groupSrv.Query.Where(o => o.USER_ID == nguoidung.ID).OrderByDescending(o => o.GROUP_NAME).FirstOrDefault().ID;//.ToList();
            Session["group_user_cbbgroup"] = groupSrv.Query.Where(o => o.USER_ID == nguoidung.ID).OrderByDescending(o => o.ID).FirstOrDefault().ID;
            return PartialView("GroupPartial", selectGroupUS);
        }

        public ActionResult LoadUserNonOfGroup(int? groupId)
        {
            var user = System.Web.HttpContext.Current.User.Identity.Name.ToUpper();
            var userSrv = IoC.Resolve<IuserService>();
            var userGroupSrv = IoC.Resolve<IUSER_GROUPService>();

            var nguoidung = ((EISContext)FXContext.Current).CurrentNguoidung;
            var firstUser = userSrv.Query.FirstOrDefault(x => x.username.ToUpper() == user.ToUpper());
            if (firstUser == null || (firstUser.ISADMIN == false && nguoidung.ISPQ != true)) return RedirectToAction("Index", "NonAuthorize");
            var firstRole = firstUser.Roles.FirstOrDefault(x => x.name.ToUpper() == "ROOT");
            //thanhpt check những thằng tồn tại ở nhóm khác thì không được hiển thị lên lưới sửa
            var idUsergroupFalse = userGroupSrv.Query.Where(o => o.GROUP_ID != groupId).Select(o => o.USER_ID).ToList();
            var nguoidungs = _INGUOIDUNGService.Query.Where(c => c.ISPQ == true).Select(c => c.TENDANGNHAP).ToList();

            var lstusers = userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true && !idUsergroupFalse.Contains(x.userid) && !nguoidungs.Contains(x.username)).ToList();
            //end thanhpt
            //var lstusers = userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true).ToList();
            var model = new UserNonGroupViewModel();
           
            if (groupId.HasValue)
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUserIdOfGroup = userGroupSrv.GetUserIdByGroupId(groupId.Value).Select(n => n.USER_ID).ToList();
                model.userIdOfGroup = lstUserIdOfGroup;
                lstUserIdOfGroups.RemoveAll(x => lstUserIdOfGroup.Contains(x));
            }
            else
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUsersOfGroups = lstusers.Where(n => lstUserIdOfGroups.Contains(n.userid)).ToList();

                lstusers.RemoveAll(x => lstUsersOfGroups.Contains(x));
            }
            model.users = lstusers;
            return View("UserNonOfGroupPartial", model);
        }

        public ActionResult LoadUserNonOfGroupCustom(int? groupId)
        {
            var user = System.Web.HttpContext.Current.User.Identity.Name.ToUpper();
            var userSrv = IoC.Resolve<IuserService>();
            var userGroupSrv = IoC.Resolve<IUSER_GROUPService>();

            var nguoidung = ((EISContext)FXContext.Current).CurrentNguoidung;
            var firstUser = userSrv.Query.FirstOrDefault(x => x.username.ToUpper() == user.ToUpper());
            if (firstUser == null || (firstUser.ISADMIN == false && nguoidung.ISPQ != true)) return RedirectToAction("Index", "NonAuthorize");
            var firstRole = firstUser.Roles.FirstOrDefault(x => x.name.ToUpper() == "ROOT");
            //thanhpt check những thằng tồn tại ở nhóm khác thì không được hiển thị lên lưới sửa
            var idUsergroupFalse = userGroupSrv.Query.Where(o => o.GROUP_ID != groupId).Select(o => o.USER_ID).ToList();

            var nguoidungs = _INGUOIDUNGService.Query.Where(c => c.ISPQ ==true).Select(c => c.TENDANGNHAP).ToList();

            var lstusers = userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true && !idUsergroupFalse.Contains(x.userid) &&  !nguoidungs.Contains(x.username)).ToList();
            
            //userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true && !idUsergroupFalse.Contains(x.userid) && x.userid != nguoidung.ID).ToList();
            //end thanhpt
            //var lstusers = userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true).ToList();
            var model = new UserNonGroupViewModel();
            if (groupId.HasValue)
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUserIdOfGroup = userGroupSrv.GetUserIdByGroupId(groupId.Value).Select(n => n.USER_ID).ToList();
                model.userIdOfGroup = lstUserIdOfGroup;
                lstUserIdOfGroups.RemoveAll(x => lstUserIdOfGroup.Contains(x));
            }
            else
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUsersOfGroups = lstusers.Where(n => lstUserIdOfGroups.Contains(n.userid)).ToList();

                lstusers.RemoveAll(x => lstUsersOfGroups.Contains(x));
            }
            model.users = lstusers;
            return View("UserNonOfGroupPartial", model);
        }

        public ActionResult LoadUserNonOfGroupEdit(int? groupId)
        {
            var user = System.Web.HttpContext.Current.User.Identity.Name.ToUpper();
            var userSrv = IoC.Resolve<IuserService>();
            var userGroupSrv = IoC.Resolve<IUSER_GROUPService>();

            var nguoidung = ((EISContext)FXContext.Current).CurrentNguoidung;
            var firstUser = userSrv.Query.FirstOrDefault(x => x.username.ToUpper() == user.ToUpper());
            if (firstUser == null || (firstUser.ISADMIN == false && nguoidung.ISPQ != true)) return RedirectToAction("Index", "NonAuthorize");
            var firstRole = firstUser.Roles.FirstOrDefault(x => x.name.ToUpper() == "ROOT");
            //thanhpt check những thằng tồn tại ở nhóm khác thì không được hiển thị lên lưới sửa
            var idUsergroupFalse = userGroupSrv.Query.Where(o => o.GROUP_ID != groupId).Select(o => o.USER_ID).ToList();
            var nguoidungs = _INGUOIDUNGService.Query.Where(c => c.ISPQ == true).Select(c => c.TENDANGNHAP).ToList();

            var lstusers = userSrv.Query.Where(x => x.GroupName.ToUpper() == firstUser.GroupName.ToUpper() && x.ISADMIN != true && !idUsergroupFalse.Contains(x.userid) && !nguoidungs.Contains(x.username)).ToList();
            //end thanhpt
            var model = new UserNonGroupViewModel();
            if (groupId.HasValue)
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUserIdOfGroup = userGroupSrv.GetUserIdByGroupId(groupId.Value).Select(n => n.USER_ID).ToList();
                model.userIdOfGroup = lstUserIdOfGroup;
                lstUserIdOfGroups.RemoveAll(x => lstUserIdOfGroup.Contains(x));
            }
            else
            {
                var lstUserIdOfGroups = userGroupSrv.GetAll().Select(n => n.USER_ID).ToList();
                var lstUsersOfGroups = lstusers.Where(n => lstUserIdOfGroups.Contains(n.userid)).ToList();

                lstusers.RemoveAll(x => lstUsersOfGroups.Contains(x));
            }
            model.users = lstusers;
            return View("UserNonOfGroupEditPartial", model);
        }

        public ActionResult LoadUserNonOfGroupCustomEdit(int? groupId)
        {
            var user = System.Web.HttpContext.Current.User.Identity.Name.ToUpper();
            var userSrv = IoC.Resolve<IuserService>();
            var userGroupSrv = IoC.Resolve<IUSER_GROUPService>();

            var nguoidung = ((EISContext)FXContext.Current).CurrentNguoidung;
            var firstUser = userSrv.Query.FirstOrDefault(x => x.username.ToUpper() == user.ToUpper());
            if (firstUser == null || (firstUser.ISADMIN == false && nguoidung.ISPQ != true)) return RedirectToAction("Index", "NonAuthorize");

EIS.FEW/Views/GroupUser/AddGroupUserPartial.cshtml
@Html.DevExpress().TextBox(txt =>
{
    txt.Name = "NameGroup";
    txt.Properties.Caption = "Tên nhóm";
    txt.Width = Unit.Pixel(600);
}).GetHtml()
<br/>
@Html.Action("LoadUserNonOfGroup", "GroupUser")
<div style="padding-top: 15px;"></div>
<div><p class="error" style="color: red;" id="ErrorAddGroup"></p></div>
<hr />
<div class="btnSaveOrCloseAddGroup" style="width: 240px; padding-left: 230px;">
    @Html.DevExpress().Button(btn => {
        btn.Name = "btnAddNewGroup";
        btn.Text = "Lưu";
        btn.Width = Unit.Pixel(100);
        btn.ClientSideEvents.Click = "funcCreateNewGroup";
    }).GetHtml()

    @Html.DevExpress().Button(btn =>
    {
        btn.Name = "btnClosePPAddGroup";
        btn.Text = "Đóng";
        btn.Width = Unit.Pixel(100);
        btn.ClientSideEvents.Click = "function(){ ppAddGroupUser.Hide(); $('#ErrorAddGroup').text(' ');}";
    }).GetHtml()
</div>

EIS.FEW/Views/GroupUser/BtnChapnhan.cshtml
@using EIS.Core.CustomView
@model UserGroupModelDetail
<div class="btnCapNhap">
        @Html.DevExpress().Button(s =>
        {
            s.ControlStyle.CssClass = "button";
            s.Name = "bt_CapNhat";
            s.Text = "Cập nhật";
            s.ClientSideEvents.Click = "SaveChange";
            s.Images.Image.IconID = IconID.SaveSave16x16;
        }).GetHtml()

        @Html.DevExpress().Button(s =>
        {
            s.Name = "bt_back";
            s.Text = "Quay lại";
            s.ClientSideEvents.Click = "function(s, e){ location.href = '/QuanLyNguoiDung/Index'}";
            s.ControlStyle.CssClass = "button";
            s.Images.Image.IconID = IconID.NavigationBackward16x16;
        }).GetHtml()
    </div>

EIS.FEW/Views/GroupUser/EditGroupUserPartial.cshtml
@Html.DevExpress().TextBox(txt =>
{
    txt.Name = "NameEditGroup";
    txt.Properties.Caption = "Tên nhóm";
    txt.Width = Unit.Pixel(600);
}).GetHtml()
<br />
@Html.Action("LoadUserNonOfGroupEdit", "GroupUser")
<div style="padding-top: 15px;"></div>
<div><p class="error" style="color: red;" id="ErrorEditGroup"></p></div>
<hr />
<div class="btnSaveOrCloseAddGroup" style="width: 240px; padding-left: 230px;">
    @Html.DevExpress().Button(btn =>
    {
        btn.Name = "btnUpdateGroup";
        btn.Text = "Lưu";
        btn.Width = Unit.Pixel(100);
        btn.ClientSideEvents.Click = "funcUpdate";
    }).GetHtml()

    @Html.DevExpress().Button(btn =>
    {
        btn.Name = "btnCloseEditFrom";
        btn.Text = "Đóng";
        btn.Width = Unit.Pixel(100);
        btn.ClientSideEvents.Click = "function(){ ppEditGroupUser.Hide(); $('#ErrorEditGroup').text(' ');}";
    }).GetHtml()
</div>

EIS.FEW/Views/GroupUser/FilterView.cshtml
@Html.DevExpress().FormLayout(settings =>
{
    settings.Name = "formLayout";
    settings.EncodeHtml = false;
    settings.Width = Unit.Percentage(100);
    settings.ColCount = 3;

    settings.Items.Add(txt =>
    {
        txt.Caption = @"Tên tài khoản ";
        txt.Name = "str_TimKiem";
        txt.Width = Unit.Percentage(50);
        txt.NestedExtensionType = FormLayoutNestedExtensionItemType.TextBox;
        txt.NestedExtension().TextBox(tb =>
        {
            tb.Properties.NullText = @"Nhập từ khóa tìm kiếm theo tên tài khoản . . .";
            tb.Width = Unit.Percentage(100);
        });
    });

    settings.Items.Add(bt =>
    {
        bt.NestedExtensionType = FormLayoutNestedExtensionItemType.Button;
        bt.Caption = @" ";
        bt.Width = Unit.Percentage(5);
        bt.NestedExtension().Button(s =>
        {
            s.Name = "bt_TimKiem";
            s.EnableTheming = false;
            s.Text = "";
            s.AllowFocus = false;
            s.RenderMode = ButtonRenderMode.Link;
            s.Images.Image.SpriteProperties.CssClass = "btnSearch";
            s.Images.Image.SpriteProperties.HottrackedCssClass = "btnSearchHottracked";
            s.Images.Image.SpriteProperties.PressedCssClass = "btnSearchPressed";
            s.ToolTip = "Tìm kiếm";
            //s.ClientSideEvents.Click = "Filter";
        });
    });

    settings.Items.Add(bt =>
    {
        bt.NestedExtensionType = FormLayoutNestedExtensionItemType.Button;
        bt.Caption = @" ";
        bt.Width = Unit.Percentage(5);
        bt.NestedExtension().Button(s =>
        {
            s.Name = "btnSave";
            s.EnableTheming = false;
            s.Text = "";
            s.AllowFocus = false;
            s.RenderMode = ButtonRenderMode.Link;
            s.Images.Image.SpriteProperties.CssClass = "btnSaveBaoCao13";
            s.Images.Image.SpriteProperties.HottrackedCssClass = "btnSaveBaoCao13Hottracked";
            s.Images.Image.SpriteProperties.PressedCssClass = "btnSaveBaoCao13Pressed";
            s.ToolTip = "Lưu thay đổi";
            s.ClientSideEvents.Click = "funcSave";
        });
    });
}).GetHtml()

EIS.FEW/Views/GroupUser/GroupPartial.cshtml
@Html.DevExpress().ComboBox(cbb =>
{
    cbb.Name = "cbbGroup";
    cbb.CallbackRouteValues = new { Action = "CbbGroupCallBack", Controller = "GroupUser" };
    cbb.Properties.ValueField = "ID";
    cbb.Properties.TextField = "GROUP_NAME";
    cbb.Properties.Caption = "Nhóm người dùng";
    cbb.ControlStyle.CssClass = "fixLeft";
    cbb.Properties.DropDownStyle = DropDownStyle.DropDownList;
    cbb.SelectedIndex = 0;
    cbb.Properties.ClientSideEvents.EndCallback = "endCbbGroup";
    cbb.Properties.ClientSideEvents.SelectedIndexChanged = "funcCbbGroupUserChange";
}).BindList(Model).GetHtml()

EIS.FEW/Views/GroupUser/HeadResourcesPartial.cshtml
@Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        //new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }
    )
@Html.DevExpress().GetScripts(
        //new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        ////new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        //new Script { ExtensionSuite = ExtensionSuite.GridView }
    )

EIS.FEW/Views/GroupUser/RolesPartialView.cshtml
@using IdentityManagement.Domain;
@model List<role>

@Html.DevExpress().CallbackPanel(
    settings =>
    {
        settings.Name = "CallbackPanel";
        settings.CallbackRouteValues = new { Controller = "GroupUser", Action = "UserRoleCallbackPanel" };
        settings.Width = Unit.Percentage(100);
        settings.SetContent(() =>
        {
            if (ViewBag.Content != null)
                ViewContext.Writer.Write(ViewBag.Content);
        });
    }).GetHtml()

EIS.FEW/Views/GroupUser/UserNonOfGroupEditPartial.cshtml
@using IdentityManagement.Domain
@using EIS.Core.CustomView
@model UserNonGroupViewModel

@Html.DevExpress().GridView(g =>
{
    g.Name = "EditUsersOfGroups";
    g.KeyFieldName = "userid";
    g.CallbackRouteValues = new { Controller = "GroupUser", Action = "LoadUserNonOfGroupEdit" };
    g.CustomActionRouteValues = new { Controller = "GroupUser", Action = "LoadUserNonOfGroupCustomEdit" };
    g.ClientSideEvents.BeginCallback = "UserOfGroupbeginCallback";
    g.CommandColumn.Visible = true;
    g.CommandColumn.SelectAllCheckboxMode = GridViewSelectAllCheckBoxMode.Page;

    g.CommandColumn.ShowSelectCheckbox = true;
    g.CommandColumn.Width = Unit.Pixel(30);
    g.SettingsLoadingPanel.Text = @"Vui lòng đợi trong giây lát!";
    g.CommandColumn.Caption = " ";
    g.Settings.ShowFilterRow = true;
    g.Settings.ShowFilterRowMenu = true;
    //g.SettingsBehavior.FilterRowMode = GridViewFilterRowMode.Auto;
    g.SettingsPager.PageSize = 10;
    g.Width = Unit.Percentage(98);

    g.Columns.Add(s =>
    {
        s.FieldName = "username";
        s.Width = Unit.Percentage(100);
        s.Caption = "Tên đăng nhập";
        s.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
        s.CellStyle.HorizontalAlign = HorizontalAlign.Left;
        s.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
    });
    //g.Width = Unit.Pixel(200);
    g.AfterPerformCallback += (s, e) =>
    {
        var grid = s as MVCxGridView;
        if (Model.userIdOfGroup.Count > 0)
        {
            foreach (var userId in Model.userIdOfGroup)
            {
                grid.Selection.SetSelectionByKey(userId, true);
            }
        }
    };
}).Bind(Model.users).GetHtml()
@*.BindToLINQ(string.Empty, string.Empty, (s, e) =>
{
    e.KeyExpression = "userid";
    e.QueryableSource = Model.users.AsQueryable();
}).GetHtml()*@

EIS.FEW/Views/GroupUser/UserNonOfGroupPartial.cshtml
@using IdentityManagement.Domain
@using EIS.Core.CustomView
@model UserNonGroupViewModel

@Html.DevExpress().GridView(g =>
{
    g.Name = "UsersOfGroups";
    g.KeyFieldName = "userid";
    g.CallbackRouteValues = new { Controller = "GroupUser", Action = "LoadUserNonOfGroup" };
    g.CustomActionRouteValues = new { Controller = "GroupUser", Action = "LoadUserNonOfGroupCustom" };
    g.CommandColumn.Visible = true;
    g.CommandColumn.SelectAllCheckboxMode = GridViewSelectAllCheckBoxMode.Page;
    g.CommandColumn.ShowSelectCheckbox = true;
    g.CommandColumn.Width = Unit.Pixel(30);
    g.SettingsLoadingPanel.Text = @"Vui lòng đợi trong giây lát!";
    g.CommandColumn.Caption = " ";
    g.Settings.ShowFilterRow = true;
    g.Settings.ShowFilterRowMenu = true;
    //g.SettingsBehavior.FilterRowMode = GridViewFilterRowMode.Auto;
    g.SettingsPager.PageSize = 10;
    g.Width = Unit.Percentage(98);

    g.Columns.Add(s =>
    {
        s.FieldName = "username";
        s.Caption = "Tên đăng nhập";
        s.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
        s.CellStyle.HorizontalAlign = HorizontalAlign.Left;
        s.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
    });
    //g.Width = Unit.Pixel(200);
    g.AfterPerformCallback += (s, e) =>
    {
        var grid = s as MVCxGridView;
        if (Model.userIdOfGroup.Count > 0)
        {
            foreach (var userId in Model.userIdOfGroup)
            {
                grid.Selection.SetSelectionByKey(userId, true);
            }
        }
        //else
        //{
        //    grid.Selection.UnselectAll();
        //}
    };
}).Bind(Model.users).GetHtml()
@*.BindToLINQ(string.Empty, string.Empty, (s, e) =>
 {
     e.KeyExpression = "userid";
     e.QueryableSource = Model.users.AsQueryable();
 }).GetHtml()*@

EIS.FEW/Views/GroupUser/UserOfGroupPartial.cshtml
@model List<IdentityManagement.Domain.user>
@Html.DevExpress().ListBox(lb =>
{
    lb.Name = "lbUsers";
    lb.CallbackRouteValues = new { controller = "GroupUser", action = "LoadUserOfGroup" };
    lb.Width = Unit.Pixel(200);
    lb.Height = Unit.Pixel(250);
    lb.Properties.ValueField = "userid";
    lb.Properties.TextField = "username";
   // lb.Properties.DataSource = ViewBag.LoaduserGroup;
    lb.Properties.Caption = "Người dùng của nhóm";
    //lb.Properties.ClientSideEvents.EndCallback = "endCbbUser";
    lb.Properties.ValueType = typeof(int);
}).BindList(Model).GetHtml()

EIS.FEW/Views/GroupUser/cbbGroupUser.cshtml
@using EIS.Core.CustomView
@model UserGroupModelDetail
<table style="margin-top: 3%;width: 35%;float: left;">
    <tr>
        <td style="float: left;">
            @Html.DevExpress().ComboBox(cbb =>
            {
                cbb.Name = "cbbGroup";
                cbb.CallbackRouteValues = new { Action = "CbbGroupCallBack", Controller = "GroupUser" };
                cbb.Properties.EnableClientSideAPI = true;
                cbb.Properties.ValueField = "ID";
                cbb.Properties.TextField = "GROUP_NAME";
                cbb.Properties.Caption = "Nhóm người dùng";
                cbb.SelectedIndex = 0;
                cbb.Properties.ClientSideEvents.EndCallback = "endCbbGroup";
                cbb.Properties.DropDownStyle = DropDownStyle.DropDownList;
                cbb.ControlStyle.CssClass = "fixLeft";
                cbb.Properties.ClientSideEvents.SelectedIndexChanged = "funcCbbGroupUserChange";

            }).BindList(Model.Groups.ToList()).GetHtml()
            <div style="padding-bottom: 35px;"></div>
            @*@Html.Partial("UserOfGroupPartial", Model.usersOfGroup);*@
            @Html.DevExpress().ListBox(lb =>
       {
           lb.Name = "lbUsers";
           lb.CallbackRouteValues = new { controller = "GroupUser", action = "LoadUserOfGroup" };
           lb.Width = Unit.Pixel(400);
           lb.Height = Unit.Pixel(250);
           lb.Properties.ValueType = typeof(int);
           lb.Properties.ValueField = "userid";
           lb.Properties.TextField = "username";
           //lb.Properties.ClientSideEvents.EndCallback = "endCbbUser";
           lb.Properties.DataSource = ViewBag.LoaduserGroup;
           lb.Properties.Caption = "Người dùng của nhóm";
       }).BindList(Model.usersOfGroup.ToList()).GetHtml()
            <div style="padding-top: 15px; margin-left: 25%;">
                @Html.DevExpress().Button(btn =>
                    {
                        btn.Name = "btnAddGroup";
                        btn.Text = "Thêm nhóm";
                        btn.ClientSideEvents.Click = "funcAddGroup";
                        btn.Images.Image.IconID = IconID.ActionsAdd16x16;
                    }).GetHtml()

                @Html.DevExpress().Button(btn =>
                    {
                        btn.Name = "btnEditGroup";
                        btn.Text = "Sửa nhóm";
                        btn.ClientSideEvents.Click = "funcEditGroup";
                        btn.Images.Image.IconID = IconID.ActionsEdit16x16devav;
                    }).GetHtml()

                @Html.DevExpress().Button(btn =>
                    {
                        btn.Name = "btnDeleteGroup";
                        btn.Text = "Xóa nhóm";
                        btn.ClientSideEvents.Click = "funcDeleteGroup";
                        btn.Images.Image.IconID = IconID.ActionsDelete16x16devav;
                    }).GetHtml()
            </div>
        </td>
    </tr>
</table>

EIS.FEW/Views/GroupUser/cbbQuyentruycap.cshtml
@using EIS.Core.CustomView
@model UserGroupModelDetail
<table style="width:100%">
    <tr>
        <td style="float:left;padding-top: 15px;width: 100%;">
            @Html.Partial("RolesPartialView", Model.Roles)
        </td>
        <td>
            @Html.DevExpress().Button(btn =>
                {
                    btn.Name = "buttonChuyenHuong";
                    btn.ToolTip = "Tạo mới nhóm quyền";
                    btn.Text = "";
                    btn.ControlStyle.CssClass = "float_left_pms";
                    btn.ControlStyle.Font.Underline = false;
                    btn.ControlStyle.BackColor = System.Drawing.Color.Transparent;
                    btn.ControlStyle.Border.BorderStyle = BorderStyle.None;
                    btn.Images.Image.Url = "~/Content/Images/Icon-flat/Add.png";
                    btn.ClientSideEvents.Click = "ChuyenhuongAddRolePms";
                }).GetHtml()
        </td>
    </tr>
</table>