EIS.FEW/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FX.Core;
using EIS.Core.IService;
using IdentityManagement.Service;
using IdentityManagement.Domain;
using EIS.Core.CustomView;
using EIS.Core.Domain;
using EIS.FEW.Models;
using IdentityManagement.Authorization;

namespace EIS.FEW.Controllers
{
    [RBACAuthorize(Roles = "Root")]
    public class PermissionController : Controller
    {
        private readonly IpermissionService _iPMSService;
        private readonly IobjectService _iServiceObj;
        private readonly IroleService _iroleService;
        private readonly ITYPE_ROLEService _iTypeRoleService;
        private readonly ILogSystemService _iLogSystemService;
        private readonly ITYPE_PERMISSIONService _ITYPE_PERMISSIONService;
        public PermissionController()
        {
            _iPMSService = IoC.Resolve<IpermissionService>();
            _iServiceObj = IoC.Resolve<IobjectService>();
            _iTypeRoleService = IoC.Resolve<ITYPE_ROLEService>();
            _iroleService = IoC.Resolve<IroleService>();
            _iLogSystemService = IoC.Resolve<ILogSystemService>();
            _ITYPE_PERMISSIONService = IoC.Resolve<ITYPE_PERMISSIONService>();

        }
        public ActionResult Index()
        {
            Session["MultiType"] = null;
            Session["MultiTypeCheckEdit"] = null;
            Session["ObjectList"] = GetAllObjectRbac();
            var result = GetAllPms();
            return View(result);
        }
        public ActionResult PERMISSIONPartial()
        {
            return PartialView("PERMISSIONPartial", GetAllPms());
        }
        public ActionResult AddNewPms(ObjectPermission obpms)
        {
            if (ModelState.IsValid && Session["MultiType"] != null)
            {
                var checkPermissionInObject =
                    _iPMSService.Query.Where(m => m.ObjectRBAC.objectid == obpms.ObjectId)
                        .Select(n => n.permissionid)
                        .ToList();
                int count = checkPermissionInObject.Count;
                if (count < 8)
                {
                    var checkname = _iPMSService.Query.FirstOrDefault(x => x.name.ToUpper() == obpms.PmsName.ToUpper());
                    if (checkname == null)
                    {

                        try
                        {
                            objectRbac objRb = new objectRbac();
                            objRb.objectid = obpms.ObjectId;

                            permission p = new permission();
                            p.AppID = 1;
                            p.name = obpms.PmsName.Trim();
                            p.Description = obpms.DesPms.Trim();
                            p.ObjectRBAC = objRb;
                            var Type_pms = new TYPE_PERMISSION();
                            string TYPE_PERMISSIONMULTI = Session["MultiType"].ToString();

                            _iPMSService.BeginTran();

                            _iPMSService.CreateNew(p);
                            Type_pms.PERMISSIONID = p.permissionid;
                            Type_pms.TYPE_PERMISSIONMULTI = TYPE_PERMISSIONMULTI;
                            Type_pms.LOAI_PERMISSION = obpms.LoaiPermission;
                            _ITYPE_PERMISSIONService.CreateNew(Type_pms);

                            _iPMSService.CommitTran();
                            _iLogSystemService.CreateNew(HttpContext.User.Identity.Name, "Thêm mới tác vụ ", "Thực hiện chức năng thêm mới tác vụ", Helper.GetIPAddress.GetVisitorIPAddress(), HttpContext.Request.Browser.Browser);
                        }
                        catch (Exception e)
                        {
                            _iPMSService.RolbackTran();
                            ViewData["EditError"] = e.Message;

                        }
                    }
                    else
                    {
                        ViewData["EditError"] = "Tên đã tồn tại, xin chọn tên khác!";
                    }
                }
                else
                {
                    ViewData["EditError"] = "Một chức năng chỉ chứa tối đa 8 tác vụ, nhóm hiện đã có 8 tác vụ, vui lòng chọn chức năng khác!";
                }
            }
            else
            {
                ViewData["EditError"] = "Bạn phải nhập đầy đủ thông tin";
            }
            Session["MultiType"] = null;
            Session["MultiTypeCheckEdit"] = null;
            return PartialView("PERMISSIONPartial", GetAllPms());
        }
        public ActionResult UpdatePms(ObjectPermission obpms)
        {
            if ((ModelState.IsValid && Session["MultiTypeCheckEdit"] == null) || (ModelState.IsValid && Session["MultiType"] != null))
            {
                var checkPermissionInObject =
                  _iPMSService.Query.Where(m => m.ObjectRBAC.objectid == obpms.ObjectId)
                      .Select(n => n.permissionid)
                      .ToList();
                int count = checkPermissionInObject.Count;
                if (count <= 8)
                {
                    var checkname = _iPMSService.Query.FirstOrDefault(x => x.name.ToUpper() == obpms.PmsName.ToUpper());
                    if (checkname == null || checkname.permissionid == obpms.PermissionId)
                    {
                        try
                        {
                            objectRbac objRecord = new objectRbac();
                            objRecord.objectid = obpms.ObjectId;
                            permission p = new permission();
                            p = _iPMSService.Getbykey(obpms.PermissionId);
                            p.name = obpms.PmsName.Trim();
                            p.Description = obpms.DesPms.Trim();
                            p.ObjectRBAC = objRecord;


                            _iPMSService.BeginTran();


                            if (Session["MultiType"] != null)
                            {
                                var Type_pms = _ITYPE_PERMISSIONService.Getbykey(obpms.PermissionId);
                                string TYPE_PERMISSIONMULTI = Session["MultiType"].ToString();
                                Type_pms.TYPE_PERMISSIONMULTI = TYPE_PERMISSIONMULTI;
                                var listrole = _iroleService.Query.Where(m => m.Permissions.Any(n => n.permissionid == obpms.PermissionId));
                                foreach (var item in listrole)
                                {
                                    var typerole = _iTypeRoleService.Query.FirstOrDefault(m => m.ROLE_ID == item.roleid) != null ? _iTypeRoleService.Query.FirstOrDefault(m => m.ROLE_ID == item.roleid).TYPE : -1;
                                    if (!(TYPE_PERMISSIONMULTI.Contains(typerole + "")))
                                    {
                                        IList<permission> listtam = item.Permissions;
                                        var bientam_PMS = listtam.FirstOrDefault(m => m.permissionid == obpms.PermissionId);
                                        listtam.Remove(bientam_PMS);
                                        item.Permissions = listtam;
                                        _iroleService.Update(item);
                                    }
                                }
                                _ITYPE_PERMISSIONService.Update(Type_pms);
                            }
                            _iPMSService.Update(p);
                            _iPMSService.CommitTran();
                            _iLogSystemService.CreateNew(HttpContext.User.Identity.Name, "Cập nhật tác vụ ", "Thực hiện chức năng cập nhật tác vụ", Helper.GetIPAddress.GetVisitorIPAddress(), HttpContext.Request.Browser.Browser);
                        }
                        catch (Exception e)
                        {
                            _iPMSService.RolbackTran();
                            ViewData["EditError"] = e.Message;
                        }
                    }
                    else
                    {
                        ViewData["EditError"] = "Tên đã tồn tại, xin chọn tên khác!";
                    }
                }
                else
                {
                    ViewData["EditError"] = "Một chức năng chỉ chứa tối đa 8 tác vụ, nhóm hiện đã có 8 tác vụ, vui lòng chọn chức năng khác!";
                }
            }
            else
            {
                ViewData["EditError"] = "Bạn phải nhập đầy đủ thông tin";
            }
            Session["MultiType"] = null;
            Session["MultiTypeCheckEdit"] = null;
            return PartialView("PERMISSIONPartial", GetAllPms());
        }
        public EmptyResult ChangeMultiType(string lstMultiType)
        {
            if (lstMultiType.Trim() != "")
                Session["MultiType"] = lstMultiType.Trim();
            else
                Session["MultiType"] = null;
            Session["MultiTypeCheckEdit"] = true;

            return new EmptyResult();
        }
        public ActionResult DeletePms(ObjectPermission obpms)
        {
            if (CheckForDeletePms(obpms.PermissionId))
            {
                permission model = _iPMSService.Getbykey(obpms.PermissionId);
                var Type_pms = _ITYPE_PERMISSIONService.Getbykey(obpms.PermissionId);

                _iPMSService.BeginTran();
                _iPMSService.Delete(model);
                _ITYPE_PERMISSIONService.Delete(Type_pms);
                _iPMSService.CommitTran();
                _iLogSystemService.CreateNew(HttpContext.User.Identity.Name, "Xóa tác vụ ", "Thực hiện chức năng Xóa tác vụ", Helper.GetIPAddress.GetVisitorIPAddress(), HttpContext.Request.Browser.Browser);
            }
            else
            {
                _iPMSService.RolbackTran();
                ViewData["EditErrorDelete"] = "Không thể xóa vì có phân quyền chứa tác vụ này!";
            }

EIS.FEW/Views/Permission/HeadResourcesPartial.cshtml
@Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout }
)
@Html.DevExpress().GetScripts()

EIS.FEW/Views/Permission/Index.cshtml
@model System.Collections.IEnumerable
@{
    ViewBag.Title = "EIS v" + EIS.FEW.RouteConfig.Version + " | Quản lý tác vụ";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}
@section HeadResources{
    @Html.Partial("HeadResourcesPartial")
}

<style>
    .dxgvTable_EIS {
        border-right: 1px solid #c0c0c0;
    }

    #gvEditing_tcFooterRow {
        color: red !important;
    }

    .btnSearch:hover {
        background-image: url('/Content/Images/Icon-flat/Search-over.png');
        width: 32px;
        height: 32px;
    }

    .btnSearch:active {
        background-image: url('/Content/Images/Icon-flat/Search.png');
        width: 32px;
        height: 32px;
    }

    .dxgvSearchPanel_EIS {
        border: 0px none !important;
        padding: 0px !important;
    }

    .float_left_pms {
        float: left;
    }

    .height_10 {
        height: 10px;
        clear: both;
    }

    .dxgvSearchPanel_EIS > table {
        float: left;
        margin-bottom: 15px;
    }
</style>
<script>
    function StoreTypePms(lstMultiTypeCheck) {
        //alert(lstMultiTypeCheck);
        lstMultiTypeCheck = $.trim(lstMultiTypeCheck);
        $.ajax({
            type: "POST",
            url: '@Url.Action("ChangeMultiType", "Permission")',
            data: { lstMultiType: lstMultiTypeCheck },
            success: function () {
                popup_CANHBAO.Show();
            }
        });
    }
    function CanhBao(lstMultiTypeCheck) {

    }
</script>
<div style="padding : 10px; margin:auto">
    @Html.DevExpress().PopupControl(
            settings =>
            {
                settings.Name = "popup_CANHBAO";
                settings.HeaderText = "Thông báo";
                settings.Width = Unit.Pixel(300);
                settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
                settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
                settings.CloseOnEscape = true;
                settings.Modal = true;
                settings.AllowDragging = true;
                settings.CloseAction = CloseAction.CloseButton;
                settings.SetContent(() =>
                {
                    ViewContext.Writer.Write("<div style=\" padding : 10px\">");
                    Html.DevExpress().Label(
                        labelSettings =>
                        {
                            labelSettings.ControlStyle.CssClass = "label";
                            labelSettings.Text = "Thay đổi phạm vi là cực kỳ nguy hiểm, sẽ ảnh hưởng tới toàn bộ dữ liệu phân quyền. Bạn có chắc muốn thay đổi?";
                        }
                    )
                    .Render();

                    ViewContext.Writer.Write("</div><div style=\" padding : 10px\"> <table><tr><td style=\"padding : 10px; margin:auto\">");

                    Html.DevExpress().Button(
                        buttonSettings =>
                        {
                            buttonSettings.Name = "btCanhbao";
                            buttonSettings.ControlStyle.CssClass = "button";
                            buttonSettings.Width = 80;
                            buttonSettings.Text = "Đồng ý";
                            buttonSettings.ClientSideEvents.Click = "function(s, e){ popup_CANHBAO.Hide(); }";
                        }
                    )
                    .Render();
                    ViewContext.Writer.Write(" </td><td style=\"padding : 10px; margin:auto\">");
                    Html.DevExpress().Button(
                        buttonSettings =>
                        {
                            buttonSettings.Name = "btnCancel_Canhbao";
                            buttonSettings.ControlStyle.CssClass = "button";
                            buttonSettings.Width = 80;
                            buttonSettings.Text = "Hủy";
                            buttonSettings.ClientSideEvents.Click = "function(s, e){ popup_CANHBAO.Hide();gvEditing.CancelEdit(); }";
                        }
                    )
                    .Render();
                    ViewContext.Writer.Write("</td></tr></table></div><b class=\"Clear\"></b>");
                });
            }).GetHtml()
</div>
<div class="height_10"></div>
@Html.DevExpress().RoundPanel(settings =>
       {
           settings.Name = "roundPanel";
           settings.AllowCollapsingByHeaderClick = false;

           settings.ShowCollapseButton = false;
           settings.EnableAnimation = false;
           settings.HeaderText = "QUẢN LÝ TÁC VỤ";
           settings.Width = Unit.Percentage(80);
       }).GetHtml()
<div class="height_10"></div>
@Html.Partial("PERMISSIONPartial", Model)
<div class="height_10"></div>

EIS.FEW/Views/Permission/PERMISSIONPartial.cshtml
@using EIS.FEW.Controllers
@{
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    var grid = Html.DevExpress().GridView(
        settings =>
        {
            settings.Name = "gvEditing";
            settings.KeyFieldName = "PermissionId";
            settings.CallbackRouteValues = new { Controller = "Permission", Action = "PERMISSIONPartial" };
            settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Permission", Action = "AddNewPms" };
            settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Permission", Action = "UpdatePms" };
            settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Permission", Action = "DeletePms" };
            settings.SettingsEditing.Mode = EIS.FEW.Helper.GridViewEditingHelper.EditMode;
            settings.SettingsBehavior.ConfirmDelete = true;
            settings.SettingsPopup.EditForm.Width = 900;
            settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.Center;
            settings.SettingsPopup.EditForm.AllowResize = true;
            settings.SettingsText.PopupEditFormCaption = "Tác vụ";
            settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.Below;
            settings.SettingsCommandButton.UpdateButton.Text = "Lưu";
            settings.SettingsCommandButton.UpdateButton.Image.IconID = IconID.SaveSave16x16;
            settings.SettingsCommandButton.CancelButton.Text = "Hủy";
            settings.SettingsCommandButton.CancelButton.Image.IconID = IconID.ActionsCancel16x16;
            settings.Width = Unit.Percentage(80);
            settings.Settings.ShowFilterRow = true;
            settings.Settings.ShowFilterRowMenu = true;

            settings.SettingsSearchPanel.Visible = true;
            settings.SettingsSearchPanel.HighlightResults = true;
            settings.SettingsText.SearchPanelEditorNullText = "Nhập từ khóa cần tìm kiếm...";
            settings.SettingsSearchPanel.ShowApplyButton = true;
            settings.SettingsCommandButton.SearchPanelApplyButton.ButtonType = GridCommandButtonRenderMode.Image;
            settings.SettingsCommandButton.SearchPanelApplyButton.Image.SpriteProperties.CssClass = "btnSearch";

            settings.SettingsContextMenu.Enabled = true;
            settings.SettingsPager.Position = PagerPosition.Bottom;
            settings.SettingsPager.PageSizeItemSettings.Visible = true;
            settings.SettingsPager.PageSizeItemSettings.Items = new string[] { "10", "15", "20", "25", "30" };
            settings.SettingsBehavior.AllowFocusedRow = false;
            settings.SettingsBehavior.AllowSelectByRowClick = true;
            settings.SettingsContextMenu.RowMenuItemVisibility.Refresh = false;
            settings.CommandColumn.Visible = true;
            settings.CommandColumn.VisibleIndex = 99;
            settings.CommandColumn.ShowNewButtonInHeader = true;
            settings.CommandColumn.ShowEditButton = true;
            settings.SettingsCommandButton.NewButton.Image.Url = "~/Content/Images/add2.png";
            settings.SettingsCommandButton.NewButton.Text = "Tạo mới";
            settings.SettingsCommandButton.NewButton.Styles.Style.ForeColor = System.Drawing.Color.White;
            settings.SettingsCommandButton.DeleteButton.Image.Url = "~/Content/Images/Delete_16x16.png";
            settings.SettingsCommandButton.EditButton.Image.Url = "~/Content/Images/Edit_16x16.png";
            settings.CommandColumn.Width = Unit.Percentage(5);
            settings.CommandColumn.ShowDeleteButton = true;
            settings.SettingsBehavior.ColumnResizeMode = ColumnResizeMode.Control;

            if (ViewData["EditErrorDelete"] != null)
            {
                settings.SetFooterRowTemplateContent(c =>
                {
                    Html.ViewContext.Writer.Write(ViewData["EditErrorDelete"]);
                });
            }

            settings.BeforeGetCallbackResult = (s, e) =>
            {
                if (ViewData["EditErrorDelete"] != null)
                {
                    MVCxGridView gridView = (MVCxGridView)s;
                    gridView.Settings.ShowFooter = true;
                }
            };

            settings.Columns.Add(s =>
            {
                s.Caption = "STT";
                s.ToolTip = "STT";
                s.EditFormSettings.Visible = DefaultBoolean.False;
                s.PropertiesEdit.EnableClientSideAPI = true;
                s.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                s.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                s.Width = Unit.Percentage(3);
            });
            settings.CustomColumnDisplayText = (send, e) =>
            {
                if (e.Column.Caption == "STT")
                {
                    e.DisplayText = (e.VisibleRowIndex + 1).ToString();
                }
            };
            settings.Columns.Add(col =>
            {
                col.FieldName = "PermissionId";
                col.Caption = "PermissionId";
                col.PropertiesEdit.EnableClientSideAPI = true;
                col.Width = 50;
                col.CellStyle.HorizontalAlign = HorizontalAlign.Center;
                col.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                col.Visible = false;
            });

            settings.Columns.Add(col =>
            {
                col.FieldName = "PmsName";
                col.Caption = "Tên tác vụ";
                col.PropertiesEdit.EnableClientSideAPI = true;
                col.Width = Unit.Percentage(15);
                col.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                col.CellStyle.Paddings.PaddingLeft = 10;
                col.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
                col.ColumnType = MVCxGridViewColumnType.TextBox;
                var colP = col.PropertiesEdit as TextBoxProperties;
                colP.MaxLength = 100;
            });
            settings.Columns.Add(col =>
            {
                col.FieldName = "DesPms";
                col.Caption = "Mô tả tác vụ";
                col.PropertiesEdit.EnableClientSideAPI = true;
                col.Width = Unit.Percentage(5);
                col.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                col.CellStyle.Paddings.PaddingLeft = 10;
                col.ColumnType = MVCxGridViewColumnType.TextBox;
                var colP = col.PropertiesEdit as TextBoxProperties;
                colP.MaxLength = 100;
                col.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
            });

            settings.Columns.Add(s =>
            {

                s.FieldName = "LoaiPermission";
                s.Caption = "Loại tác vụ";
                s.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
                s.Width = Unit.Percentage(5);
                s.ToolTip = "Loại tác vụ";
                s.CellStyle.Paddings.PaddingLeft = 10;
                s.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                s.PropertiesEdit.EnableClientSideAPI = true;
                s.ColumnType = MVCxGridViewColumnType.ComboBox;
                var comboPro = s.PropertiesEdit as ComboBoxProperties;
                comboPro.Width = Unit.Percentage(100);
                comboPro.DataSource = EIS.Core.Common.Common.SelectListPermissionItems;
                comboPro.ValueField = "Key";
                comboPro.TextField = "Value";
                //comboPro.Columns.Add("name", "Chọn một chức năng", Unit.Percentage(100));
                comboPro.TextFormatString = "{0}";
                comboPro.DisplayFormatString = "{0}";
                comboPro.ValueType = typeof(string);
                comboPro.DropDownStyle = DropDownStyle.DropDown;
                s.Settings.AllowAutoFilterTextInputTimer = DefaultBoolean.False;
                s.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
            });
            settings.Columns.Add(s =>
            {
                s.FieldName = "ObjectId";
                s.Caption = "Thuộc chức năng";
                s.ToolTip = "Thuộc chức năng";
                s.CellStyle.Font.Bold = true;
                s.CellStyle.Paddings.PaddingLeft = 10;
                s.HeaderStyle.HorizontalAlign = HorizontalAlign.Center;
                s.PropertiesEdit.EnableClientSideAPI = true;
                s.ColumnType = MVCxGridViewColumnType.ComboBox;
                s.Width = Unit.Percentage(15);
                var comboPro = s.PropertiesEdit as ComboBoxProperties;
                comboPro.Width = Unit.Percentage(100);
                comboPro.DataSource = Session["ObjectList"];
                comboPro.ValueField = "objectid";
                comboPro.TextField = "name";
                comboPro.Columns.Add("name", "Chọn một chức năng", Unit.Percentage(100));
                comboPro.TextFormatString = "{0}";
                comboPro.DisplayFormatString = "{0}";
                comboPro.ValueType = typeof(string);
                comboPro.DropDownStyle = DropDownStyle.DropDown;
                s.Settings.AllowAutoFilterTextInputTimer = DefaultBoolean.False;
                s.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
            });
            settings.Columns.Add(col =>
            {
                col.Width = Unit.Percentage(15);
                col.FieldName = "MultiTypeName";
                col.Caption = "Phạm vi tác vụ";
                col.Settings.AutoFilterCondition = AutoFilterCondition.Contains;
                col.SetEditItemTemplateContent(c =>
                {
                    Html.DevExpress().CheckBoxList(chSettings =>
                    {
                        chSettings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s, e){ StoreTypePms(s.GetSelectedValues());}";
                        //chSettings.Properties.ClientSideEvents.SelectedIndexChanged = "function (s, e){ StoreTypePms(e.command);}";
                        chSettings.Name = "chk_" + c.Column.FieldName + "_" + c.ItemIndex;
                        chSettings.Width = Unit.Percentage(100);
                        chSettings.ControlStyle.CssClass = "float_left_pms";
                        chSettings.Properties.RepeatLayout = RepeatLayout.Flow;
                        chSettings.Properties.RepeatDirection = RepeatDirection.Horizontal;
                        chSettings.ToolTip = "Phạm vi tác vụ";
                        chSettings.Properties.TextField = "Text";
                        chSettings.Properties.ValueField = "Value";
                        chSettings.Properties.ValueType = typeof(int);
                        chSettings.PreRender = (sender, e) =>
                        {
                            ASPxCheckBoxList cbl = (ASPxCheckBoxList)sender;
                            foreach (ListEditItem item in cbl.Items)
                            {
                                string pms = item.Text;
                                string subName = pms.Substring(0, 1);
                                bool CheckReal = (subName == " ") ? true : false;
                                if (CheckReal)
                                {
                                    item.Selected = true;
                                }
                            }
                        };
                    }).BindList(PermissionController.GetRealSelectListItems(Convert.ToString(DataBinder.Eval(c.DataItem, "MultiTypeName")))).Render();
                });
            });

            settings.PreRender = (sender, e) =>
            {
                ((MVCxGridView)sender).StartEdit(-1);

            };
        });

    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()